static_resources:
  listeners:
    - name: kafka_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9093
      listener_filters:
        # Inspect TLS to allow filter chain selection
        - name: envoy.filters.listener.tls_inspector
          typed_config: {}
      filter_chains:
        - filters:
            - name: envoy.filters.network.kafka_broker
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
                stat_prefix: kafka_broker
                force_response_rewrite: true
                id_based_broker_address_rewrite_spec:
                  rules:
                    - id: 1
                      host: localhost
                      port: 9093
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp
                cluster: kafka_cluster
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              require_client_certificate: true
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/kafka/secrets/kafka.crt
                    private_key:
                      filename: /etc/kafka/secrets/kafka.key
                validation_context:
                  trusted_ca:
                    filename: /etc/kafka/secrets/ca.crt
  clusters:
    - name: kafka_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: kafka_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: kafka-broker
                      port_value: 9093
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_certificates:
              - certificate_chain:
                  filename: /etc/kafka/secrets/kafka.crt
                private_key:
                  filename: /etc/kafka/secrets/kafka.key
            validation_context:
              trusted_ca:
                filename: /etc/kafka/secrets/ca.crt
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 } 